spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/job-platform
          jwk-set-uri: http://localhost:18080/realms/job-platform/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:18080
  realm: job-platform
  client-id: job-platform-app
  api-client-id: job-platform-api
  api-client-secret: job-platform-api-secret
  admin-username: admin
  admin-password: admin
